//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterServcie.ServicePicture {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePicture.IServicePicture")]
    public interface IServicePicture {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePicture/CombineTextPicture", ReplyAction="http://tempuri.org/IServicePicture/CombineTextPictureResponse")]
        string CombineTextPicture(string url, string en, string ru);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePicture/CombineTextPicture", ReplyAction="http://tempuri.org/IServicePicture/CombineTextPictureResponse")]
        System.Threading.Tasks.Task<string> CombineTextPictureAsync(string url, string en, string ru);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePictureChannel : MasterServcie.ServicePicture.IServicePicture, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePictureClient : System.ServiceModel.ClientBase<MasterServcie.ServicePicture.IServicePicture>, MasterServcie.ServicePicture.IServicePicture {
        
        public ServicePictureClient() {
        }
        
        public ServicePictureClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePictureClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePictureClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePictureClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CombineTextPicture(string url, string en, string ru) {
            return base.Channel.CombineTextPicture(url, en, ru);
        }
        
        public System.Threading.Tasks.Task<string> CombineTextPictureAsync(string url, string en, string ru) {
            return base.Channel.CombineTextPictureAsync(url, en, ru);
        }
    }
}
