//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterServcie.ServiceWord {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWord.IServiceWord")]
    public interface IServiceWord {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWord/TakeWordTranslate", ReplyAction="http://tempuri.org/IServiceWord/TakeWordTranslateResponse")]
        string[] TakeWordTranslate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWord/TakeWordTranslate", ReplyAction="http://tempuri.org/IServiceWord/TakeWordTranslateResponse")]
        System.Threading.Tasks.Task<string[]> TakeWordTranslateAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWordChannel : MasterServcie.ServiceWord.IServiceWord, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWordClient : System.ServiceModel.ClientBase<MasterServcie.ServiceWord.IServiceWord>, MasterServcie.ServiceWord.IServiceWord {
        
        public ServiceWordClient() {
        }
        
        public ServiceWordClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWordClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWordClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWordClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] TakeWordTranslate() {
            return base.Channel.TakeWordTranslate();
        }
        
        public System.Threading.Tasks.Task<string[]> TakeWordTranslateAsync() {
            return base.Channel.TakeWordTranslateAsync();
        }
    }
}
